#!/usr/local/bin/node

var reporter  = require('nodeunit').reporters.default,

    MYSQL_CONNECTION_DATA = {
      host: '127.0.0.1',
      port: '3306',
      type: 'mysql',
      user: 'root',
      password: '',
      database: 'sequel_orm_test'
    };

process.chdir(__dirname);
reporter.run([ 'test' ], null, function() {
  process.exit();
});
